pages = [{"l":"index.html#","e":false,"i":"","n":"PPS-22-Scooby","t":"PPS-22-Scooby","d":"","k":"static","x":""},
{"l":"org/unibo/scooby.html#","e":false,"i":"","n":"org.unibo.scooby","t":"org.unibo.scooby","d":"","k":"package","x":""},
{"l":"org/unibo/scooby.html#main-94c","e":false,"i":"","n":"main","t":"main(): Unit","d":"org.unibo.scooby","k":"def","x":""},
{"l":"org/unibo/scooby/example.html#","e":false,"i":"","n":"org.unibo.scooby.example","t":"org.unibo.scooby.example","d":"","k":"package","x":""},
{"l":"org/unibo/scooby/example/hello.html#","e":false,"i":"","n":"org.unibo.scooby.example.hello","t":"org.unibo.scooby.example.hello","d":"","k":"package","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorld$.html#","e":false,"i":"","n":"HelloWorld","t":"HelloWorld","d":"org.unibo.scooby.example.hello","k":"object","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorld$.html#apply-2bd","e":false,"i":"","n":"apply","t":"apply(): Behavior[Greet]","d":"org.unibo.scooby.example.hello.HelloWorld","k":"def","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorld$$Greet.html#","e":false,"i":"","n":"Greet","t":"Greet(whom: String, replyTo: ActorRef[Greeted])","d":"org.unibo.scooby.example.hello.HelloWorld","k":"class","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorld$$Greeted.html#","e":false,"i":"","n":"Greeted","t":"Greeted(whom: String, from: ActorRef[Greet])","d":"org.unibo.scooby.example.hello.HelloWorld","k":"class","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorldBot$.html#","e":false,"i":"","n":"HelloWorldBot","t":"HelloWorldBot","d":"org.unibo.scooby.example.hello","k":"object","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorldBot$.html#apply-fffffd76","e":false,"i":"","n":"apply","t":"apply(max: Int): Behavior[Greeted]","d":"org.unibo.scooby.example.hello.HelloWorldBot","k":"def","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorldMain$.html#","e":false,"i":"","n":"HelloWorldMain","t":"HelloWorldMain extends App","d":"org.unibo.scooby.example.hello","k":"object","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorldMain$.html#apply-2bd","e":false,"i":"","n":"apply","t":"apply(): Behavior[SayHello]","d":"org.unibo.scooby.example.hello.HelloWorldMain","k":"def","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorldMain$.html#system-0","e":false,"i":"","n":"system","t":"system: ActorSystem[SayHello]","d":"org.unibo.scooby.example.hello.HelloWorldMain","k":"val","x":""},
{"l":"org/unibo/scooby/example/hello/HelloWorldMain$$SayHello.html#","e":false,"i":"","n":"SayHello","t":"SayHello(name: String)","d":"org.unibo.scooby.example.hello.HelloWorldMain","k":"class","x":""},
{"l":"org/unibo/scooby/example/ping.html#","e":false,"i":"","n":"org.unibo.scooby.example.ping","t":"org.unibo.scooby.example.ping","d":"","k":"package","x":""},
{"l":"org/unibo/scooby/example/ping/Echo$.html#","e":false,"i":"","n":"Echo","t":"Echo","d":"org.unibo.scooby.example.ping","k":"object","x":""},
{"l":"org/unibo/scooby/example/ping/Echo$.html#apply-2bd","e":false,"i":"","n":"apply","t":"apply(): Behavior[Ping]","d":"org.unibo.scooby.example.ping.Echo","k":"def","x":""},
{"l":"org/unibo/scooby/example/ping/Echo$$Ping.html#","e":false,"i":"","n":"Ping","t":"Ping(message: String, response: ActorRef[Pong])","d":"org.unibo.scooby.example.ping.Echo","k":"class","x":""},
{"l":"org/unibo/scooby/example/ping/Echo$$Pong.html#","e":false,"i":"","n":"Pong","t":"Pong(message: String)","d":"org.unibo.scooby.example.ping.Echo","k":"class","x":""},
{"l":"org/unibo/scooby/main.html#","e":false,"i":"","n":"main","t":"main","d":"org.unibo.scooby","k":"class","x":""}];