name: Publish Scaladoc to GitHub Pages

on:
  push:
    branches:
      - develop
      - config/repo-configuration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt/launchers
            ~/.coursier
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-

      - name: Install sbt
        run: |
          echo "sbt.version=1.5.5" > ./project/build.properties
          sbt sbtVersion

      - name: Generate Scaladoc
        run: |
          sbt doc
          ls -lah ./target/scala-3.3.3/api/

      
