name: Publish Documentation

on:
  pull_request:
    branches:
      - develop
    types: [closed]

permissions:
  contents: write

jobs:
  publish-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt/launchers
            ~/.coursier
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-

      - name: Install sbt
        run: |
          echo "sbt.version=1.10.0" > ./project/build.properties
          sbt sbtVersion

      - name: Generate Scaladoc
        run: |
          sbt doc
          mkdir -p ./docs && cp -r ./target/scala-3.4.2/api/ ./docs

      - name: Deploy auth docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs