name: Publish Scaladoc to GitHub Pages

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt/launchers
            ~/.coursier
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
            ${{ runner.os }}-sbt-

      - name: Install sbt
        run: |
          echo "sbt.version=1.10.0" > ./project/build.properties
          sbt sbtVersion

      - name: Run coverage test
        run: sbt clean coverage test

  test:
    runs-on: ubuntu-latest
    needs:
      - coverage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt/launchers
            ~/.coursier
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
            ${{ runner.os }}-sbt-

      - name: Install sbt
        run: |
          echo "sbt.version=1.10.0" > ./project/build.properties
          sbt sbtVersion

      - name: Run Tests
        run: sbt test

  publish-docs:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt/launchers
            ~/.coursier
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-

      - name: Install sbt
        run: |
          echo "sbt.version=1.10.0" > ./project/build.properties
          sbt sbtVersion

      - name: Generate Scaladoc
        run: |
          sbt doc
          mkdir -p ./docs && cp -r ./target/scala-3.3.3/api/ ./docs
          ls -lah ./docs

      - name: Deploy auth docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
